/***
 * Image/J Plugins
 * Copyright (C) 2002-2008 Jarek Sacha
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
 *
 * You should have received a copy of the GNU Lesser General Public
 * License along with this library; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place, Suite 330, Boston, MA  02111-1307  USA
 *
 * Latest release available at http://sourceforge.net/projects/ij-plugins/
 */

/*
* RegionGrowingView.java
*
* Created on February 18, 2008, 1:44 PM
*/

package net.sf.ij_plugins.grow;

import net.sf.ij_plugins.ui.multiregion.MultiRegionManagerView;

import javax.swing.*;
import javax.swing.GroupLayout.Alignment;
import javax.swing.LayoutStyle.ComponentPlacement;

/**
 * @author ac4566
 */
public class RegionGrowingView extends javax.swing.JPanel {

    private final RegionGrowingModel model;
    private final RunAction runAction;

    /**
     * Creates new form RegionGrowingView
     */
    public RegionGrowingView() {
        model = new RegionGrowingModel(multiRegionManagerView.getModel());
        runAction = new RunAction(model);

        initComponents();
    }

    /**
     * This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        regionsSeparator = new JSeparator();
        regionsLabel = new JLabel();
        jSeparator2 = new JSeparator();
        runButton = new JButton();

        regionsLabel.setText("Seed Selection");

        runButton.setAction(runAction);

        GroupLayout layout = new GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(Alignment.LEADING)
                                .addComponent(jSeparator2, Alignment.TRAILING, GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                                .addGroup(layout.createSequentialGroup()
                                        .addComponent(regionsLabel)
                                        .addPreferredGap(ComponentPlacement.UNRELATED)
                                        .addComponent(regionsSeparator, GroupLayout.DEFAULT_SIZE, 451, Short.MAX_VALUE))
                                .addComponent(multiRegionManagerView, GroupLayout.DEFAULT_SIZE, 531, Short.MAX_VALUE)
                                .addComponent(runButton, Alignment.TRAILING))
                        .addContainerGap())

        );
        layout.setVerticalGroup(
                layout.createParallelGroup(Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(Alignment.TRAILING)
                                .addComponent(regionsLabel)
                                .addComponent(regionsSeparator, GroupLayout.PREFERRED_SIZE, 10, GroupLayout.PREFERRED_SIZE))
                        .addGap(10, 10, 10)
                        .addComponent(multiRegionManagerView, GroupLayout.DEFAULT_SIZE, 286, Short.MAX_VALUE)
                        .addPreferredGap(ComponentPlacement.UNRELATED)
                        .addComponent(jSeparator2, GroupLayout.PREFERRED_SIZE, GroupLayout.DEFAULT_SIZE, GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(runButton)
                        .addContainerGap())

        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JSeparator jSeparator2;
    private final MultiRegionManagerView multiRegionManagerView = new MultiRegionManagerView();
    private JLabel regionsLabel;
    private JSeparator regionsSeparator;
    private JButton runButton;
    // End of variables declaration//GEN-END:variables

}
